# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  autenticador:
    image: dotnet-render
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:      
      - TZ=America/Sao_Paulo
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}